const FOOD_ENUMS = {
	CATEGORIES: {
		//MEAT: "meat",
		PASTRIES: "pastries",
		DRINKS: "drinks",
		SWALLOW: "swallow",
		TRADS: "trads",
		SOUPS: "soups",
		RICE: "rice",
		PROTEIN: "protein",
		SIDES: "sides",
		OTHERS: "others",
	},

	SUB_CATEGORIES: {
		SAUCES:"sauces",
		MEAT: "meat",
		FISH: "fish",
		CHICKEN: "chicken",
		TURKEY: "turkey",
		GOAT: "goat",
		EGGS: "eggs",
		PASTRIES: "pastries",
		DRINKS: "drinks",
		SWALLOW: "swallow",
		TRADS: "trads",
		SOUPS: "soups",
		RICE: "rice",
		PROTEIN: "protein",
		SEAFOOD: "seafood",
		SAUSAGE: "sausage",
		SHRIMP: "shrimp",
		LOBSTER: "lobster",
		CRAB: "crab",
		CALAMARI: "calamari",
		FRUIT: "fruit",
		STEW: "stew",
		PASTA: "pasta",
		SALAD: "salad",
		VEGETABLES: "vegetables",
		PLANTAIN: "plantain",
		BEANS: "beans",
		JUICE: "juice",
		SODA: "soda",
		WATER: "water",
		WINE: "wine",
		BEER: "beer",
		SMOOTHIE: "smoothie",
		JOLLOF: "jollof",
		FRIED: "fried",
		WHITE: "white",
		COCONUT: "coconut",
		CAKE: "cake",
		BREAD: "bread",
		PIE: "pie",
		DONUT: "donut",
		MUFFIN: "muffin",
		SAUCE: "sauce",
		SIDES: "sides",
		OTHERS: "others",
	},
};

const CATEGORY_SUBCATEGORY_MAP = {
	protein:  ["protein", "meat", "fish", "chicken", "turkey", "goat", "eggs", "seafood", "sausage", "shrimp", "lobster", "crab", "calamari"],
	soups:    ["soups", "stew", "sauce"],
	rice:     ["rice", "jollof", "fried", "white", "coconut", "pasta", "sauce"],
	swallow:  ["swallow", "sauce"],
	sides:    ["sides", "plantain", "beans", "salad", "vegetables", "fruit", "sauce"],
	pastries: ["pastries", "cake", "bread", "pie", "donut", "muffin"],
	drinks:   ["drinks", "juice", "soda", "water", "wine", "beer", "smoothie"],
	trads:    ["trads"],
	others:   ["others"],
};

const getCategoryValues = () => Object.values(FOOD_ENUMS.CATEGORIES);
const getSubCategoryValues = () => Object.values(FOOD_ENUMS.SUB_CATEGORIES);
const getCategorySubCategoryMap = () => CATEGORY_SUBCATEGORY_MAP;

module.exports = {
	FOOD_ENUMS,
	CATEGORY_SUBCATEGORY_MAP,
	getCategoryValues,
	getSubCategoryValues,
	getCategorySubCategoryMap,
};
